### ISSUE TITLE
Doesnt Work / Statics 7 / ...

### ISSUE THREAD

**Issue by PaulCodeDisaster** [FranklinWaller/Pokemon-TCG#1]
Hello

I tried to use your script on XAMPP but it makes no Screen. Only a withe screem and in  my Mozilla title "Sample App"

I looked at the index file , there is needed "/static/bundle.js" but its not in the Package,,,,
Cann you please help me

**Comment by FranklinWaller** [comment]
You need to build it, using webpack. But you have better luck making a project from scratch because this was for me a test on how to use models in a project.
